### ISSUE TITLE
crash with rstudio and boost::spirit

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/rvle#17]
To reproduce the bug, we have to launch the simulation of file generic_with_header.vpz of record package record.meteo (which relies on pkg vle.reader  which is linked to boost::spirit) : it works with R and it crashes on rstudio.

It seems that the problem occurs on vle/reader/table_file_reader.hpp:109 in the instantiation of the grammar of boost spirit (classic).

Note: I haven't found any tool for debugging this in rstudio specifically.

**Comment by rtrepos** [comment]
The carsh seems to be due to symbols of boost::spirit that are replaced in rstudio by those imported from the plugin of record.meteo. A fix is to set --visibility=hidden in gcc flags of record.meteo pkg.

**Comment by quesnel** [comment]
Since VLE2, the rvle binary package is alone and does not depend of VLE dll. So, this kind of error must not appear.
