### ISSUE TITLE
rvle compiling under ubuntu 15.10

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/rvle#18]
Error reported:

$ R CMD INSTALL rvle
checking for Boost headers version >= 0.0.0... yes
checking for Boost's header version... 
configure: error: invalid value: boost_major_version=
ERROR: configuration failed for package ‘rvle’

Note: vle, packages are installed without error

**Comment by quesnel** [comment]
Update the boost.m4 script will fix the problem.
