### ISSUE TITLE
crash on ubuntu 15.10 when using rstudio

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/rvle#19]
Crash directly when loading rvle in rstudio
To reproduce:
library(rvle)

On a simple R session, it works

**Comment by sguyader** [comment]
I had the same problem in Manjaro Linux 15.12, it's crashing only when loading rvle. Reproduced in 2 different versions of RStudio. I get this in the rsession log:
`29 Jan 2016 00:59:32 [rsession-sguyader] ERROR Unexpected exception: std::bad_alloc; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:3304`

**Comment by quesnel** [comment]
These errors seem to be due to a conflict libraries (boost). Do you use
the version of rstudio provided by the editor? by the linux
distribution? Or by source code recompilation?

**Comment by sguyader** [comment]
I tried 2 binary versions provided by the Arch Linux AUR repo. I could not compile from the rstudio github repo because of some error at compilation time. I will try other versions and report. I have boost 1.60 on my machine.

**Comment by quesnel** [comment]
I think that rvle, built with the OS boost libraries, tries to link with
the boost libraries provided by RStudio (Certainly not the same boost
version): an ABI conflict. 

Three solutions to test:
- Use the same boost version to build both rvle and Rstudio
- Build rvle in static
- Use the boost Rstudio library to build rvle

**Comment by sguyader** [comment]
OK, I succeeded by installing "rstudio-desktop-git" from the ArchLinux User Repository, which actually automates pulling the source from github and compiling rstudio with the distro's dependencies.
I don't don't know for other distros. However, when one tries to configure rstudio compilation, there's a "install-boost" script which downloads the version 1.50 boost library by default. By editing the script, it should be possible specify the same boost version to download as the one used to build rvle.

**Comment by quesnel** [comment]
Since VLE2, the rvle binary package is alone and does not depend of VLE dll. So, this kind of error must not appear.
