### ISSUE TITLE
symbol length_error unfound when loading rvle on windows

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/rvle#21]
I got the following error when loading rvle (library rvle):

Le point d'entrée de procédure _ZNSt12length_errorD2Ev est introuvable dasn la bibliothèque de liens dynamiques libstdc++-6.dll

- vle-1.1.2
- R version 3.2.3 (RGui, not rstudio)
- windows 7

vle and gvle work and it has already worked on a similar platform.

**Comment by rtrepos** [comment]
Note: readRegistry provides the right path c:\vle-1.1.2

**Comment by quesnel** [comment]
_ZNSt12length_errorD2Ev is an error from std::length_error::~length_errr().

So, perhaps this error is a missing try/catch in the C/C++ RVLE source code?

**Comment by rtrepos** [comment]
There was a conflict with libstdc++-6.dll provided into 
c:\windows\system (from 2012)
and the one provided by vle (from 2011)
By replacing the one on the system it worked.

**Comment by rtrepos** [comment]
This is the same problem reported into this issue: #8
