### ISSUE TITLE
win: launching simulation leads to an error

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/rvle#24]
rvle.log is filled with:

Error in rvle_run: fail to spawn

The other functionnalities, looking at experiment conditions, changing the output plugin of views seem ok.

On windows 7 with vle-2.0.0-alpha1

**Comment by quesnel** [comment]
The rvle package was badly build. New beta2 binary for Win32 is ok.

[1] http://www.vle-project.org/pub/vle/2.0/2.0.0-beta2/rvle_2.0.0-4.zip
