### ISSUE TITLE
win R-3.5.0 ABI changed

### ISSUE THREAD

**Issue by eric-casellas** [vle-forge/rvle#26]
under Windows with the latest R stable version (3.5.0), the rvle compiled package for windows doesn't load. (it works well with R-3.4.4)

error message : 
Error: package or namespace load failed for ‘rvle’:
 package ‘rvle’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

**Comment by quesnel** [comment]
We need to provide binary package for both R 3.5 and R 3.4?

**Comment by quesnel** [comment]
Fix in the Beta2 Win32 binary available on vle-project.org website [1]


[1] http://www.vle-project.org/pub/vle/2.0/2.0.0-beta2/rvle_2.0.0-4.zip
