### ISSUE TITLE
Error when loading a vpz from rvle.

### ISSUE THREAD

**Issue by rtrepos** [vle-forge/rvle#28]
On windows 8 (or seven) the errror occured : 

"Failed to initialized prefix from registry. Try to "
                     "use the current executable to determine the prefix "
                     "but access to cmake, vle, curl or wget will fail." (PathWin 32 line 115)

**Comment by quesnel** [comment]
Does this happen for any vpz files? With VLE 2.0.2 and R > 3.5?

**Comment by quesnel** [comment]
Closing now. Feel free to reopen. Thanks.

**Comment by rtrepos** [comment]
I tried it on Windows 7 using vle -2.0.2 (default installer)
This happens only with Rstudio.
It seems the VLE_BASEPATH is not built successfully from the Windows Registry (the key is empty).
Not sure why this is related to rstudio.

**Comment by quesnel** [comment]
> This happens only with Rstudio.

Don't use Rstudio :p

**Comment by quesnel** [comment]
The `VLE_BASEPATH` is referenced in: https://github.com/vle-forge/vle/blob/master/src/vle/utils/Context.cpp#L130 and in the CMake scripts.

**Comment by rtrepos** [comment]
To fix this problem, choose to use R 32bits in Rstudio. If possible and depending on the version of Rstudio. I think that the use of 32bits version of R in Rstudio is deprecated.
